AllCops:
  Include:
    - !ruby/regexp /.*\.rake\z/
    - Gemfile
    - Guardfile
    - Rakefile
    - config.ru
  Exclude:
    - vendor/**/*
    - db/schema.rb
  RunRailsCops: true

# pending rails 4 upgrade
Rails/ActionFilter:
  Enabled: false

Output:
  Exclude:
    - config/unicorn.rb

Style/GuardClause:
  MinBodyLength: 4

Style/TrailingComma:
  EnforcedStyleForMultiline: comma

Style/Documentation:
  Enabled: false
