language: ruby

rvm:
  - 2.1.5

script:
  - bundle exec rake
  - bundle exec rubocop -RD

before_script:
  - cp config/database.travis.yml config/database.yml
  - bundle exec rake db:create db:schema:load
