development:
  adapter: postgresql
  encoding: unicode
  database: track_development
  pool: 5

test:
  adapter: postgresql
  encoding: unicode
  database: track_test
  pool: 5

production:
  adapter: postgresql
  encoding: unicode
  database: track_production
  pool: 5
